# Generated by Django 2.1.10 on 2019-10-02 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_auto_20190930_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='permission',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Permission'),
        ),
    ]
