# Generated by Django 2.1.10 on 2019-08-09 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='moblie',
            new_name='mobile',
        ),
    ]
